**NumPy Guide Débutant**

**1. Installation et chargement de NumPy**

In [79]:
import numpy as np

**2. Création des données avec NumPy**

**2.1 Créer un numPy array avec une liste/liste de liste(matrice)**

In [4]:
#Création à partir d'une liste
liste = [1,2,3,4,5]  #Définition de la liste d'élément
array_with_liste = np.array(liste)
print(array_with_liste)

[1 2 3 4 5]


In [5]:
#Création à partir d'une matrice

In [6]:
#Création d'une matrice à partir d'une liste de liste (matrice)
matrice = [[1,2,3], [4,5,6], [7,8,9]]
array_with_matrice = np.array(matrice)
print(array_with_matrice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**2.2 Créer un numPy array à partir de fonctions intégrées**

In [9]:
#Créer un NumPy array à partir de la fonction zéros
array_zeros = np.zeros((3,3))
print(array_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
#Créer un NumPy array à partir de la fonction ones
array_ones = np.ones((4,2))
print(array_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
#Créer un NumPy array avec la fonction eye 
array_eye = np.eye(6)#Pour créer la matrice d'identité
print(array_eye)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [16]:
#Créer un NumPy array avec la fonction arange: pour créer des nombres entre le minimum et le maximum avec un pas
array_arange = np.arange(0, 10, 2)
print(array_arange)

[0 2 4 6 8]


In [20]:
#Créer un NumPy array avec la fonction linspace #Générer une séquence de nombre 
#entre deux valeurs données avec un nombre de points donné
array_linspace = np.linspace(0, 1, 10)#Très utile pour les graphiques 
print(array_linspace)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [26]:
#Créer un NumPy array de valeurs aléatoires avec la fonction random
array_random = np.random.random((4,3))#Utile pour initialiser les poids dans les réseaux de neurones, générer des données
print(array_random) 

[[0.31398659 0.32996772 0.89753378]
 [0.57837785 0.81819652 0.81064827]
 [0.71587602 0.03314088 0.95468645]
 [0.68332942 0.95951529 0.98036405]]


**3. Fonctions mathématiques et statistiques avec NumPy**

In [27]:
#Fonctions mathématiques basique
array1 = array_with_liste
array_sum = np.sum(array1)
array_mean = np.mean(array1)
array_std = np.std(array1)
array_min = np.min(array1)
array_max = np.max(array1)
array_sqrt = np.sqrt(array1)
array_abs = np.abs(array1)
array_power = np.power(array1, 2)
array_exp = np.exp(array1)
array_log = np.log(array1)
array_sin = np.sin(array1)
array_median = np.median(array1)
array_sum

np.int64(15)

In [28]:
array_median

np.float64(3.0)

**4. Manipulation des données**

In [29]:
#Produit matriciel
matrice = ([1, 2, 3], [4, 5 , 6], [7, 8, 9])
produit_matriciel = np.dot(array_with_matrice, array_with_matrice)
print(produit_matriciel)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [30]:
#Transposée
transposee = np.transpose(array_with_matrice)
print(transposee)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [31]:
#Inversion pour les matrices carrées non singulière
inverse = np.linalg.inv(array_eye)
print(inverse)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [32]:
#Déterminant
determinant = np.linalg.det(array_eye)
print(determinant)

1.0


**5: Accéder aux éléments, séléctionner, modifier et mettre à jour un numpy array**

In [33]:
#Accès aux éléments
array1 = np.array([1, 2, 3, 4, 5])
premier_element = array1[0]
print(premier_element)

1


In [34]:
#Modifier un élément
array1[0] = 10
print(array1)

[10  2  3  4  5]


In [39]:
#Sélection des éléments qui respectent une condition 
condition = array1 > 5
elements_respectant_condition= array1[array1 > 2 ]
elements_respectant_condition

array([10,  3,  4,  5])

In [40]:
condition = array1 > 3
condition
indices = np.where(array1 > 3)
indices

(array([0, 3, 4]),)

In [42]:
array1 > 5

array([ True, False, False, False, False])

In [45]:
#Utilisation d'un np.where
indices = np.where(array1 > 5)
elements_respectant_condition_np_where = array1[indices]
print(elements_respectant_condition_np_where)

[10]


In [52]:
#Slicing et indexation avancé
array6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
premiere_ligne = array6[0, :]
premiere_ligne

array([1, 2, 3])

In [56]:
première_colonne = array6[:, 0]
première_colonne

array([1, 4, 7])

In [62]:
#sous matrices
sous_matrice = array6[1:3, 1:3]
sous_matrice

array([[5, 6],
       [8, 9]])

In [63]:
#Indéxation avancée
lignes = [0, 1]
colonnes = [1, 2]
elements_selectionnes = array6[lignes, colonnes]
elements_selectionnes

array([2, 6])

In [65]:
#Opérations élémentaires et diffusion 
array7 = np.array([1, 2, 3])
array8 = np.array([4, 5, 6])

#Additions éléementaire
array_addition = array7 + array8
array_addition 

array([5, 7, 9])

In [66]:
#Multiplication élémentaire
array_multiplication = array7 * array8
array_multiplication

array([ 4, 10, 18])

In [68]:
#Diffusion
array9 = np.array([[1,2,3], [4, 5, 6], [7, 8, 9 ]])
array10 = np.array([1, 2, 3])
array9 + array10

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

**6. Redimensionnement, append, type de données, taille etc**

In [70]:
#Redimensionné le NumPy array
array3 = np.arange(9)
array3_redimensionne = array3.reshape((3,3))
print(array3_redimensionne)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [71]:
array3 = np.arange(9)
array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [73]:
#Ajouter des éléments dans un NumPy array
array1_allonge = np.append(array1, [6, 7, 8])
print(array1_allonge)

[10  2  3  4  5  6  7  8]


In [74]:
#Connaitre les caractéristiques d'un NumPy array
array_with_matrice.shape #Dimension de l'array

(3, 3)

In [77]:
#Connaitre le type de l'objet
type(array_with_matrice) #type de l'objet

numpy.ndarray

In [78]:
#Connaitre le type des éléments
array1.dtype

dtype('int64')