**Numpy**

In [1]:
import numpy as np

In [4]:
arr=np.array([-3,-4,1,4,5])
print('mean', arr.mean())
print('min', arr.min())
print('max', arr.max())
print('median', np.median(arr))

mean 0.6
min -4
max 5
median 1.0


In [5]:
arr[3]

np.int64(4)

In [6]:
arr[2]

np.int64(1)

In [7]:
arr[0]

np.int64(-3)

In [8]:
arr[1:3]

array([-4,  1])

In [10]:
arr[:3]

array([-3, -4,  1])

In [11]:
arr[1:]

array([-4,  1,  4,  5])

In [12]:
arr[::2]

array([-3,  1,  5])

In [13]:
arr[::3]

array([-3,  4])

In [14]:
arr[arr>0]

array([1, 4, 5])

In [15]:
arr[2]=15
arr

array([-3, -4, 15,  4,  5])

In [16]:
arr[arr<0]=0
arr

array([ 0,  0, 15,  4,  5])