**Numpy**

In [3]:
import numpy as np

In [5]:
a=np.array([1.0,2,3,4])
print(a)
print(type(a))

[1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [6]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [8]:
zeros_arr=np.zeros((6,6))
zeros_arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
ones_arr=np.ones(6)
ones_arr

array([1., 1., 1., 1., 1., 1.])

In [11]:
c=np.linspace(0,15,4)
c

array([ 0.,  5., 10., 15.])

In [12]:
print(np.arange(10))
print(np.arange(5,10))
print(np.arange(0,10,4))

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[0 4 8]


In [13]:
M=np.arange(20).reshape(5,4)
M

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [14]:
print(M.T)

[[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]
